import React from 'react';
import DisplayGraph from './GraphthWrapper.jsx';
import './app.css';

function App() {
  return (
    <div className="App">
      <div className="info-container">
        <div classname="description1">
          <h1>Suisse Agricultural Organizations in the Web</h1>
        </div>
        <div classname="description2">
        <p> This plot displays 1.734 agricultural websites (green), their interlinkages, and their interlinkages with websites of non-agricultural organizations (pink). Explore this webscape to get an bubble-indipendent impression of the versatility of suisse agriculture. The crawler is still running and data regularly updated.  </p>
        </div>
      </div> 
      <div className="graph-container">
        <DisplayGraph />
      </div>  
      <div className="info-container">
        <div className="description1">
          <p>
            This network graph displays the web-network of suisse agricultural organizations.
             Greenish nodes are websites, where the home-domain conatains a keyword connected to agriculture (Landwirtschaft, agriculture, fattoria,etc. ).
             The node size depends on the wesites in-degree. That is, if a website is linked to by other websites, the websites node is bigger. The edges represent links between websites.            
          </p>  
          <p>
            The data for this graph was generated by a recursive beautiful soup based crawler (created by me with much help 
            from some chatbots and the sources the bots used). It was started on the website of a suisse agricultural organization and crawled for links leading to external websites. 
            If the home-domain of the external websites contained a keyword related to agriculture, crawling was continued. 
            The crawler was designed to be very gentle (depth 1, sleep time between requests, respecting robots.txt).    
            The Graph is displayed with react, graphology and sigma.js.
          </p>  
        </div>
        <div className="description2">
          <p>
            The Graph has some interactive features. You can: </p>
            <ul>
              <li>zoom in and out</li>
              <li>search for nodes</li>
              <li>click on nodes to open url in a new tab</li>
              <li>Randomly pick an agricultural node and open in a new tab (hit the R button at the bottom of the controls)</li>
              <li>Render the the graph with ForceAtlas2 
                (a technique that "turns strucutral proximities into visual proximities, 
                facilitating the analysis and in particular the analysis of social networks") </li>
            </ul>      
        </div>
        <div className="description3">         
          <p>
            If you you are curious about this project, want to support its further development, or 
            wish that I provide more documentation, please:</p>
             <ul>
                <li>leave a reaction at my <a href="www.linkedin.com/in/moritz-maurer-agriculturalsociologist" title="Linktitle">linkedIn account</a></li>
                <li>contact me via this email adress: agriculturalorganizationsintheweb[at]gmail.com</li> 
            </ul> 
            <p>
            This website was created by me, Moritz Maurer,
             a suisse based agricultural sociologist. 
             The data and the graph are for illustrative purposes only
              and may not be accurate. Use the information at your own risk.
          </p>
        </div>
      </div>
    </div>
  );
}

export default App;