import React from 'react';
import DisplayGraph from './GraphthWrapper.jsx';
import './app.css';

function App() {
  return (
    <div className="App">
      <div className="header-container">
        <div className="header">
          <h1>The Swiss Agricultural Webscape</h1>
        </div>
        <div className="descriptionheader1">
        <p> This plot displays 2'211 Swiss agricultural websites (green) and their interlinkage. 
          Explore this webscape to get a bubble-indipendent impression of the versatility of Swiss agriculture. 
          The crawler that generated the data is still running and the data is regularly updated. 
            This is a demo. Currently, the graph performs imperfect on smartphones.</p>
        </div>
      </div> 
      <div className="graph-container">
        <DisplayGraph />
      </div>  
      <div className="info-container">
        <div className="description1">
          <p>
          The greenish nodes represent websites where the home domain contains a keyword related to agriculture (Landwirtschaft, agriculture, fattoria, etc.).
          The node size depends on the website's in-degree. That is, if a website is linked by many other websites, its node is larger. The edges represent links between websites.
          </p>
          <p>
          The data for this graph was generated by a recursive Beautiful Soup-based crawler (created by me with much help
            from some chatbots and the sources they used). It was started on the website of a Swiss agricultural organization and crawled for links leading to external websites.
            If the home domain of the external website contained one of the agriculture keywords, crawling was continued.
            The crawler was designed to crawl gently (depth 1, sleep time between requests, respecting robots.txt).
            The graph is displayed using <a href="https://sim51.github.io/react-sigma/" title="Linktitle">React, Graphology, and Sigma.js.</a>
            The code for the crawler and the graph is available in this github repository.
          </p>  
        </div>
        <div className="description2">
          <p>
            The Graph has some interactive features. You can: </p>
            <ul>
              <li>Zoom in and out</li>
              <li>Search for nodes</li>
              <li>Click on nodes to open URL in a new tab</li>
              <li>Randomly pick an agricultural node and open in a new tab</li>
              <li>Render the the graph with ForceAtlas2 
                (a technique that <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0098679" title="Linktitle"> "turns strucutral proximities into visual proximities, 
                facilitating the analysis and in particular the analysis of social networks"</a>)</li>
              <li> view non-agricultural websites that were referenced by agricultural websites (the graph will render slowly on computers with limited memory)</li>
            </ul>      
        </div>
        <div className="description3">         
          <p>
            If you you are curious about this project, want to support its further development, or 
            wish that I provide more documentation, please:</p>
             <ul>
                <li>Leave a reaction at my <a href="https://linkedin.com/in/moritz-maurer-agriculturalsociologist" title="Linktitle">linkedIn account</a></li>
                <li>Or contact me via this email adress: agriculturalwebscapes[at]protonmail.com</li> 
            </ul> 
            <p>
            This website was created by me, Moritz Maurer,
             a Swiss based agricultural sociologist. 
             The data and the graph are for illustrative purposes only
              and may not be accurate. Use the information at your own risk.
          </p>
        </div>
      </div>
    </div>
  );
}

export default App;